### ISSUE TITLE
Referecing deployment_id between jobs.

### ISSUE THREAD

**Issue by g0pinath-metricon** [chrnorm/deployment-action#32]
I have a need to run a script with private runner that is Windows Server.
This action is not compatible with windows runner, and so I have split the jobs, where the first job creates the deployment and then uploads the deployment_id as artifact.

The second job runs the script on private runner.

The third job downloads the artifacts and sets the deployment id as env var and I have tried passing the deployment id as env var but the action is complaining with below error.
Error: HttpError: Invalid value for parameter 'deployment_id': null is NaN
Error: Invalid value for parameter 'deployment_id': null is NaN

Stage 1
DBUP-Create-GitDeployment:
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: pwsh 
    steps:
      - name: Create deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          initial_status: in_progress
          token: "${{ env.Password }}"
          environment: uat-jl  
      - name: Export deployment_id to file
        run: |
            ${{ steps.deployment.outputs.deployment_id }} | out-file deployment_id.txt
      - name: Upload deployment_id as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deployment_id
          path: deployment_id.txt
  -------
Stage 3
  DBUP-Git-Deployment-Status-Update:
    runs-on: ubuntu-latest
    needs: DBUP-Start-Deployment
    defaults:
      run:
       shell: pwsh 
    steps:
      - name: Download the deployment_id 
        uses: actions/download-artifact@v2
        with:
          name: deployment_id
      - name: Set deloyment_id as envvar
        run: |
              $env:deployment_id = Get-content deployment_id.txt
              Write-Output "printing file contents"
              Get-content deployment_id.txt
              Write-Output "printing env var"
              $env:deployment_id
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ env.Password }}"
          state: "success"
          deployment_id: "${{ env.deployment_id }}"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ env.Password }}"
          state: "failure"
          deployment_id: "${{ env.deployment_id }}"

**Comment by crqra** [comment]
You can specify a job's outputs, and use them in other jobs:

```
...
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Setup deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          status: pending

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Update deployment status (in progress)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ github.token }}
          state: in_progress
          deployment_id: ${{ needs.setup.outputs.deployment_id }}
...
```
