### ISSUE TITLE
Example for passing status to inactive on PR closed

### ISSUE THREAD

**Issue by y-nk** [chrnorm/deployment-action#42]
```
name: "Wipe environment"

on:
  pull_request:
    types: [closed]

jobs:
  wipe:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Remove from S3
      uses: vitorsgomes/s3-rm-action@master
      with:
        args: --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        PATH_TO_DELETE: /pr-${{ github.event.pull_request.number }}

      - uses: chrnorm/deployment-status@releases/v1
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: inactive
```

Question is simple: how to retrieve the `deployment_id` ?
