### ISSUE TITLE
`production-environment` is default false when environment used is `production`

### ISSUE THREAD

**Issue by piotrekkr** [chrnorm/deployment-action#61]
Hello. 

Just noticed that documentation specifies:
```
production-environment | (Optional) Specifies if the given environment is one that end-users  directly interact with. Default: true when environment is production and  false otherwise.
```
but GitHub API returns `"production_environment": false` when asked about created deployment:
```
[
  {
    "url": "https://api.github.com/repos/XXXXX/XXXXXX/deployments/571000164",
    "id": 571000164,
    "node_id": "DE_kwDODNDcKM4iCMVk",
    "task": "deploy",
    "original_environment": "production",
    "environment": "production",
    "description": "Deploy of v1.704.0",
    "created_at": "2022-05-26T08:18:42Z",
    "updated_at": "2022-05-26T08:19:34Z",
    "statuses_url": "https://api.github.com/repos/XXXXX/XXXXXX/deployments/571000164/statuses",
    "repository_url": "https://api.github.com/repos/XXXXX/XXXXXX",
    "creator": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "sha": "b7209186793095ca0c4bb72103f507b5645d76d0",
    "ref": "v1.704.0",
    "payload": {},
    "transient_environment": false,
    "production_environment": false,
    "performed_via_github_app": null
  }
]
```
I'm using this action like this:
```
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment-url: "${{ env.APP_VERSION_URL}}"
          environment: "production"
          initial-status: "in_progress"
          description: "Deploy of ${{ steps.version.outputs.ref }}"
          log-url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          ref: "${{ steps.version.outputs.ref }}"
```

Am I doing something wrong? Thanks.
