### ISSUE TITLE
Unexpected input(s) 'state' for 'in_progress'

### ISSUE THREAD

**Issue by catcombo** [chrnorm/deployment-action#65]
I tried to set 'in_progress' state for deployment instead of 'pending' and got the error:
```
Warning: Unexpected input(s) 'state', valid inputs are ['repo', 'owner', 'initial-status', 'token', 'log-url', 'description', 'environment', 'environment-url', 'auto-merge', 'ref', 'sha', 'task', 'required-contexts', 'payload', 'transient-environment', 'production-environment', 'auto-inactive', 'github-base-url']
```
Workflow code:
```yaml
- name: Create GitHub deployment
  uses: chrnorm/deployment-action@v2
  id: deployment
  with:
    token: '${{ github.token }}'
    environment: production
    state: 'in_progress'
```
