### ISSUE TITLE
Cannot set deployment status

### ISSUE THREAD

**Issue by hazcod** [chrnorm/deployment-action#9]
Instead of changing the status of a running deployment, it seems to create a new one as if the deployment_id variable wasn't given.

```yaml
name: Deploy
on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Terraform
    runs-on: ubuntu-latest
    steps:

    - uses: chrnorm/deployment-action@v1.1.1
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target-url: https://cluster.ironpeak.be/
        environment: production
        initial_status: in_progress
    
    - run: exit 1

    - uses: chrnorm/deployment-action@v1.1.1
      name: "Set GitHub Deployment: Success"
      if: success()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - uses: chrnorm/deployment-action@v1.1.1
      name: "Set GitHub Deployment: Failed"
      if: failure()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

```

Deployments for the same commit: 
![afbeelding](https://user-images.githubusercontent.com/5222512/76292326-4b478a80-62af-11ea-8882-11a6ca354503.png)

And you can see the commit failed here in the CI/CD run: https://github.com/ironPeakServices/infrastructure/runs/497252378?check_suite_focus=true

**Comment by hazcod** [comment]
I see no `deployment_id` variable in either action.yaml or src/index.ts as input?

**Comment by chrnorm** [comment]
Hey @hazcod, to update the deployment status you'll want to use my other action: [chrnorman/deployment-status@relases/v1](https://github.com/chrnorm/deployment-status).

This action "deployment-action" only creates the deployment and won't update the deployment status.

I just realised that my other action, "deployment-status" isn't yet published to the GitHub marketplace so I'll work on publishing it so it's a bit more discoverable.

Here's what I'm using in my own pipelines currently:

```
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://website.com
          environment: production
...
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://website.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://website.com
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
```
